### ISSUE TITLE
Is it working in 4.4.3?

### ISSUE THREAD

**Issue by rlyacht** [lgvr123/musescore-soloanalyser#1]
I've very happily used for soloanalyser for some time, and it's not longer working for me.   When I start musescore, I do see the three plugins, and I can enable them.  They appear in the Plugins menu, but nothing happens when I highlight some measure and click on soloanalyser.

Musescore Info:  OS: macOS 13.5, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

Plugin: I tried it with both the .tar.gz and .zip of 1.4.7.  I unpacked and moved soloanalyse to ~/Documents/Plugins/

**Comment by lgvr123** [comment]
Hi, thanks for notifying me the issue. The MU team broke many plugins with their 4.4 update. I will see if I can make this plugin working under 4.4.

**Comment by rlyacht** [comment]
That would be great, thanks!

**Comment by lgvr123** [comment]
MU4.4 compatible versions are released in the release [1.4.9](https://github.com/lgvr123/musescore-soloanalyser/releases/tag/1.4.9).

The **"Interactive" is not available** for now in the MU4.4 version. The Colour chooser dialog being no longer available in MU4.4.
